// Action for Context API
export enum RecipeAction {
  FETCH_RECIPES = 'FETCH_RECIPES',
  CLEAR_RECIPES = 'CLEAR_RECIPES',
  SHOW_QUERY = 'SHOW_QUERY',
  SHOW_RETRY = 'SHOW_RETRY',
  DISMISS_QUERY = 'DISMISS_QUERY',
  DISMISS_RETRY = 'DISMISS_RETRY',
  IS_LOADING = 'IS_LOADING'
}
